{{- range .Values.programmingLanguage }}
{{- $language := . }}
{{- range $.Values.applicationMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-tester-{{ $language }}-{{ . }}-deployment
spec:
  {{- if eq . "producer" }}
  replicas: {{ $.Values.replicas.producer }}
  {{- else }}
  replicas: {{ $.Values.replicas.consumer }}
  {{- end }}
  selector:
    matchLabels:
      app: kafka-tester-{{ $language }}-{{ . }}
  template:
    metadata:
      labels:
        app: kafka-tester-{{ $language }}-{{ . }}
        {{- include "kafka-test-client.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafka-test-client.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ $.Chart.Name }}-{{ $language }}-{{ . }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default (printf "%s-%s-%s" . $.Chart.AppVersion $language) }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: {{ $.Values.bootstrapServers }}
          - name: MOTIVATION_TOPIC
            value: {{ $.Values.topic }}
          - name: APPLICATION_MODE
            value: {{ . }}
          - name: ENABLE_STATISTICS
            value: {{ quote $.Values.enableStatistics | default "false" }}
          {{- if eq $.Values.enableStatistics true }}
          - name: STATISTICS_COLLECTOR_URL
            value: {{ $.Values.statisticsCollectorUrl }}
          {{- end }}
          {{- if eq . "producer" }}
          - name: ENABLE_SSL
            value: {{ quote $.Values.enableSSL }}
          - name: NUM_SAMPLES
            value: {{ quote $.Values.producerConfigurations.sampleSize }}
          - name: BATCH_SIZE
            value: {{ quote $.Values.producerConfigurations.batchSize }}
          - name: SLEEP_TIME
            value: {{ quote $.Values.producerConfigurations.sampleIntervalInSeconds }}
          - name: ENABLE_COMPACTED_TOPIC
            value: {{ quote $.Values.producerConfigurations.enableCompactTopic | default "false" }}
          - name: COMPACTED_KEY_POOL_SIZE
            value: {{ quote $.Values.producerConfigurations.compactedKeyPoolSize | default "50" }}
          {{- end }}
          {{- if eq . "consumer" }}
          - name: MOTIVATION_CONSUMER_GROUP_NAME
            value: {{ $.Values.consumerConfigurations.consumerGroupPrefix }}{{ $language }}-{{ . }}
          {{- end }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}