name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run build script
        run: bash build.sh

      - name: Logout from DockerHub
        run: docker logout

      - name: Tag successful build
        if: success()
        uses: actions/github-script@v5
        with:
          script: |
            const buildNumber = process.env.BUILD_NUMBER;
            const tagName = `${buildNumber}`;
            const { owner, repo } = context.repo;
            await github.rest.git.createRef({
              owner,
              repo,
              ref: `refs/tags/${tagName}`,
              sha: context.sha
            });